#!/bin/bash

if [ -e $1 ]
then
	echo "$1 exists!"
	recycle_path=~/RECYCLE
	if [ -d $recycle_path ]
	then
		echo "Recycle exists"
	else
		mkdir ~/RECYCLE
		echo "RECYCLE dir created"
	fi

	gzip $1
	mv $1.gz ~/RECYCLE
	echo "$1 moved to RECYCLE"

else
	echo "Incorrect file name!"
fi
